x-shared-env: &shared-env
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "root"
  POSTGRES_PORT: 5432
  POSTGRES_DBNAME: "packngo"
  POSTGRES_HOST: "db"

services:
  db:
    image: postgres:16-alpine
    command: postgres -c config_file=/etc/postgresql.conf
    shm_size: "4gb"
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    ports:
      - "6932:5432"
    volumes:
      - ./docker/postgresql/postgresql.conf:/etc/postgresql.conf
      - ./data/postgresql:/var/lib/postgresql/data
      - ./docker/postgresql/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      <<: *shared-env
      ALLOW_IP_RANGE: 0.0.0.0/0
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      timeout: 5s
      retries: 300
  server:
    build:
      context: server
    restart: on-failure
    volumes:
      - ./server:/usr/src/app
      - /usr/src/api/node_modules
    ports:
      - "3000:3000"
    environment:
      <<: *shared-env
    env_file:
      - path: ./server/.env
    depends_on:
      - db
  frontend:
    build:
      context: ./front
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
  reverseproxy:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/local.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - server
      - adminer

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
